version: "3"

tasks:
  run:
    cmds:
      - docker run --net host ghcr.io/Samir984/status

  run-db:
    cmds:
      - docker run --net host -d -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=status postgres

  build:
    cmds:
      - docker build . -t ghcr.io/Samir984/status

  publish:
    cmds:
      - docker image push ghcr.io/Samir984/status
